apiVersion: v1
kind: Pod
metadata:
    name: html-pod
    labels:
        env: testing
        region: IN
        app: html
spec:
    containers:
    - name: myhtml-con
      image: 173129/dockerimage1
---
apiVersion: v1
kind: Service
metadata:
  name: html-svc
  labels:
    app: html
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30002
    port: 8080
    targetPort: 8080
  selector:
    app: html
---

